branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
      required_pull_request_reviews:
        required_approving_review_count: 1
      enforce_admins: true
      restrictions:
        apps: []
        users: []
        teams: ["maintainers"]