apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-services-config
data:
  services: |
    - name: gsmrsvd-rzpa7sugpfgdc5rx7tnx4r-j2ded8mh
      protocol: HTTP
      network: default
      health_check:
        port: 8080
        path: /health
    - name: gsmrsvd-rzpa7sugpfgdc5rx7tnx4r-9x48x7w0
      protocol: HTTP
      network: default
      health_check:
        port: 8080
        path: /health
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
spec:
  selector:
    app: monitoring-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP