name: Authentication
on: [push]

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
          access_token_lifetime: '3600s'
          access_token_scopes: 'https://www.googleapis.com/auth/cloud-platform'