name: Verify Search Configuration

on:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: api-for-warp-drive
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Check Secrets Configuration
      run: |
        gcloud compute ssh mcp-server --zone=us-west1-b --tunnel-through-iap --command='
          echo "Checking search configuration:"
          gcloud secrets list --format="table(name)" --filter="name:google_*"
        '
