name: Deploy to GCP VM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: api-for-warp-drive
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure SSH for IAP tunnel
      run: |
        gcloud compute config-ssh
        gcloud compute config-ssh --remove
        gcloud compute config-ssh --internal-ip

    - name: Deploy to VM
      run: |
        gcloud compute ssh mcp-server --zone=us-west1-b --tunnel-through-iap --command="
          cd /home && \
          sudo rm -rf api-for-warp-drive && \
          sudo git clone https://github.com/C2100-PR/api-for-warp-drive.git && \
          cd api-for-warp-drive && \
          sudo chmod +x scripts/*.sh && \
          sudo ./scripts/setup.sh && \
          sudo -E npm install && \
          sudo -E npm start"
