name: Deploy to GCP VM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: api-for-warp-drive
          export_default_credentials: true

      - name: Deploy to VM
        env:
          PROJECT_ID: api-for-warp-drive
          ZONE: us-west1-b
          VM_NAME: mcp-server
          REPO_URL: https://github.com/C2100-PR/api-for-warp-drive.git
          SCRIPT_DIR: /home/api-for-warp-drive
          LOCAL_SCRIPT_DIR: scripts
        run: |
          echo "Starting deployment to VM: ${VM_NAME} in zone: ${ZONE}"

          gcloud compute ssh ${VM_NAME} \
            --zone=${ZONE} \
            --tunnel-through-iap \
            --command="
              echo 'Connected to VM: ${VM_NAME}';
              cd /home || exit 1;
              
              echo 'Removing existing repository directory if it exists...';
              sudo rm -rf api-for-warp-drive;
              
              echo 'Cloning repository...';
              sudo git clone ${REPO_URL};
              
              echo 'Setting up repository permissions...';
              sudo chmod +x ${SCRIPT_DIR}/${LOCAL_SCRIPT_DIR}/*.sh;
              
              echo 'Running setup script...';
              sudo ${SCRIPT_DIR}/${LOCAL_SCRIPT_DIR}/setup.sh;
              
              echo 'Installing npm dependencies...';
              cd ${SCRIPT_DIR} && sudo -E npm install;
              
              echo 'Installing service scripts...';
              sudo ${SCRIPT_DIR}/${LOCAL_SCRIPT_DIR}/install-service.sh;
              
              echo 'Deployment steps completed successfully.';
            "
          
          echo "Deployment to VM completed."