name: Deploy to GCP VM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: api-for-warp-drive
          export_default_credentials: true
      - name: Deploy
        run: |
          gcloud compute ssh mcp-server \
            --zone=us-west1-b \
            --tunnel-through-iap \
            --command="
              cd /home;
              sudo rm -rf api-for-warp-drive;
              sudo git clone https://github.com/C2100-PR/api-for-warp-drive.git;
              cd api-for-warp-drive;
              sudo chmod +x scripts/*.sh;
              sudo ./scripts/setup.sh;
              sudo -E npm install;
              sudo ./scripts/install-service.sh;
            "