# Test Search API workflow
name: Test Search API

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - uses: actions/checkout@v4

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
        service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: api-for-warp-drive
        install_components: 'gke-gcloud-auth-plugin'

    - name: Test Search on VM
      run: |
        gcloud compute ssh mcp-warp01 --zone=us-west1-b --tunnel-through-iap --command='
          curl -X POST http://localhost:3000/api/search \
            -H "Content-Type: application/json" \
            -d "{\"query\":\"coaching 2100 latest\"}"
        '